/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppRecoverIndexRouteImport } from './routes/_app.recover.index'
import { Route as AppGuideIndexRouteImport } from './routes/_app.guide.index'
import { Route as AppAssessIndexRouteImport } from './routes/_app.assess.index'
import { Route as AppGuideSearchRouteImport } from './routes/_app.guide.search'
import { Route as AppGuideSavedRouteImport } from './routes/_app.guide.saved'
import { Route as AppAssessSafetyRouteImport } from './routes/_app.assess.safety'
import { Route as AppAssessRedFlagRouteImport } from './routes/_app.assess.red-flag'
import { Route as AppAssessProcessingRouteImport } from './routes/_app.assess.processing'
import { Route as AppAssessLocationRouteImport } from './routes/_app.assess.location'
import { Route as AppAssessActivityRouteImport } from './routes/_app.assess.activity'
import { Route as AppRecoverSummaryIdRouteImport } from './routes/_app.recover.summary.$id'
import { Route as AppRecoverSessionIdRouteImport } from './routes/_app.recover.session.$id'
import { Route as AppRecoverActivityIdRouteImport } from './routes/_app.recover.activity.$id'
import { Route as AppGuideArticleIdRouteImport } from './routes/_app.guide.article.$id'
import { Route as AppAssessResultIdRouteImport } from './routes/_app.assess.result.$id'
import { Route as AppAssessQuestionsTypeRouteImport } from './routes/_app.assess.questions.$type'
import { Route as AppAssessFollowupIdRouteImport } from './routes/_app.assess.followup.$id'
import { Route as AppAssessCarePlanIdRouteImport } from './routes/_app.assess.care-plan.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverIndexRoute = AppRecoverIndexRouteImport.update({
  id: '/recover/',
  path: '/recover/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideIndexRoute = AppGuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessIndexRoute = AppAssessIndexRouteImport.update({
  id: '/assess/',
  path: '/assess/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideSearchRoute = AppGuideSearchRouteImport.update({
  id: '/guide/search',
  path: '/guide/search',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideSavedRoute = AppGuideSavedRouteImport.update({
  id: '/guide/saved',
  path: '/guide/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessSafetyRoute = AppAssessSafetyRouteImport.update({
  id: '/assess/safety',
  path: '/assess/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessRedFlagRoute = AppAssessRedFlagRouteImport.update({
  id: '/assess/red-flag',
  path: '/assess/red-flag',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessProcessingRoute = AppAssessProcessingRouteImport.update({
  id: '/assess/processing',
  path: '/assess/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessLocationRoute = AppAssessLocationRouteImport.update({
  id: '/assess/location',
  path: '/assess/location',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessActivityRoute = AppAssessActivityRouteImport.update({
  id: '/assess/activity',
  path: '/assess/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverSummaryIdRoute = AppRecoverSummaryIdRouteImport.update({
  id: '/recover/summary/$id',
  path: '/recover/summary/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverSessionIdRoute = AppRecoverSessionIdRouteImport.update({
  id: '/recover/session/$id',
  path: '/recover/session/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverActivityIdRoute = AppRecoverActivityIdRouteImport.update({
  id: '/recover/activity/$id',
  path: '/recover/activity/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideArticleIdRoute = AppGuideArticleIdRouteImport.update({
  id: '/guide/article/$id',
  path: '/guide/article/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessResultIdRoute = AppAssessResultIdRouteImport.update({
  id: '/assess/result/$id',
  path: '/assess/result/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessQuestionsTypeRoute = AppAssessQuestionsTypeRouteImport.update({
  id: '/assess/questions/$type',
  path: '/assess/questions/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessFollowupIdRoute = AppAssessFollowupIdRouteImport.update({
  id: '/assess/followup/$id',
  path: '/assess/followup/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessCarePlanIdRoute = AppAssessCarePlanIdRouteImport.update({
  id: '/assess/care-plan/$id',
  path: '/assess/care-plan/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/assess/activity': typeof AppAssessActivityRoute
  '/assess/location': typeof AppAssessLocationRoute
  '/assess/processing': typeof AppAssessProcessingRoute
  '/assess/red-flag': typeof AppAssessRedFlagRoute
  '/assess/safety': typeof AppAssessSafetyRoute
  '/guide/saved': typeof AppGuideSavedRoute
  '/guide/search': typeof AppGuideSearchRoute
  '/assess/': typeof AppAssessIndexRoute
  '/guide/': typeof AppGuideIndexRoute
  '/recover/': typeof AppRecoverIndexRoute
  '/assess/care-plan/$id': typeof AppAssessCarePlanIdRoute
  '/assess/followup/$id': typeof AppAssessFollowupIdRoute
  '/assess/questions/$type': typeof AppAssessQuestionsTypeRoute
  '/assess/result/$id': typeof AppAssessResultIdRoute
  '/guide/article/$id': typeof AppGuideArticleIdRoute
  '/recover/activity/$id': typeof AppRecoverActivityIdRoute
  '/recover/session/$id': typeof AppRecoverSessionIdRoute
  '/recover/summary/$id': typeof AppRecoverSummaryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/assess/activity': typeof AppAssessActivityRoute
  '/assess/location': typeof AppAssessLocationRoute
  '/assess/processing': typeof AppAssessProcessingRoute
  '/assess/red-flag': typeof AppAssessRedFlagRoute
  '/assess/safety': typeof AppAssessSafetyRoute
  '/guide/saved': typeof AppGuideSavedRoute
  '/guide/search': typeof AppGuideSearchRoute
  '/assess': typeof AppAssessIndexRoute
  '/guide': typeof AppGuideIndexRoute
  '/recover': typeof AppRecoverIndexRoute
  '/assess/care-plan/$id': typeof AppAssessCarePlanIdRoute
  '/assess/followup/$id': typeof AppAssessFollowupIdRoute
  '/assess/questions/$type': typeof AppAssessQuestionsTypeRoute
  '/assess/result/$id': typeof AppAssessResultIdRoute
  '/guide/article/$id': typeof AppGuideArticleIdRoute
  '/recover/activity/$id': typeof AppRecoverActivityIdRoute
  '/recover/session/$id': typeof AppRecoverSessionIdRoute
  '/recover/summary/$id': typeof AppRecoverSummaryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/assess/activity': typeof AppAssessActivityRoute
  '/_app/assess/location': typeof AppAssessLocationRoute
  '/_app/assess/processing': typeof AppAssessProcessingRoute
  '/_app/assess/red-flag': typeof AppAssessRedFlagRoute
  '/_app/assess/safety': typeof AppAssessSafetyRoute
  '/_app/guide/saved': typeof AppGuideSavedRoute
  '/_app/guide/search': typeof AppGuideSearchRoute
  '/_app/assess/': typeof AppAssessIndexRoute
  '/_app/guide/': typeof AppGuideIndexRoute
  '/_app/recover/': typeof AppRecoverIndexRoute
  '/_app/assess/care-plan/$id': typeof AppAssessCarePlanIdRoute
  '/_app/assess/followup/$id': typeof AppAssessFollowupIdRoute
  '/_app/assess/questions/$type': typeof AppAssessQuestionsTypeRoute
  '/_app/assess/result/$id': typeof AppAssessResultIdRoute
  '/_app/guide/article/$id': typeof AppGuideArticleIdRoute
  '/_app/recover/activity/$id': typeof AppRecoverActivityIdRoute
  '/_app/recover/session/$id': typeof AppRecoverSessionIdRoute
  '/_app/recover/summary/$id': typeof AppRecoverSummaryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/home'
    | '/assess/activity'
    | '/assess/location'
    | '/assess/processing'
    | '/assess/red-flag'
    | '/assess/safety'
    | '/guide/saved'
    | '/guide/search'
    | '/assess/'
    | '/guide/'
    | '/recover/'
    | '/assess/care-plan/$id'
    | '/assess/followup/$id'
    | '/assess/questions/$type'
    | '/assess/result/$id'
    | '/guide/article/$id'
    | '/recover/activity/$id'
    | '/recover/session/$id'
    | '/recover/summary/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/home'
    | '/assess/activity'
    | '/assess/location'
    | '/assess/processing'
    | '/assess/red-flag'
    | '/assess/safety'
    | '/guide/saved'
    | '/guide/search'
    | '/assess'
    | '/guide'
    | '/recover'
    | '/assess/care-plan/$id'
    | '/assess/followup/$id'
    | '/assess/questions/$type'
    | '/assess/result/$id'
    | '/guide/article/$id'
    | '/recover/activity/$id'
    | '/recover/session/$id'
    | '/recover/summary/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/home'
    | '/_app/assess/activity'
    | '/_app/assess/location'
    | '/_app/assess/processing'
    | '/_app/assess/red-flag'
    | '/_app/assess/safety'
    | '/_app/guide/saved'
    | '/_app/guide/search'
    | '/_app/assess/'
    | '/_app/guide/'
    | '/_app/recover/'
    | '/_app/assess/care-plan/$id'
    | '/_app/assess/followup/$id'
    | '/_app/assess/questions/$type'
    | '/_app/assess/result/$id'
    | '/_app/guide/article/$id'
    | '/_app/recover/activity/$id'
    | '/_app/recover/session/$id'
    | '/_app/recover/summary/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover/': {
      id: '/_app/recover/'
      path: '/recover'
      fullPath: '/recover/'
      preLoaderRoute: typeof AppRecoverIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide/': {
      id: '/_app/guide/'
      path: '/guide'
      fullPath: '/guide/'
      preLoaderRoute: typeof AppGuideIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/': {
      id: '/_app/assess/'
      path: '/assess'
      fullPath: '/assess/'
      preLoaderRoute: typeof AppAssessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide/search': {
      id: '/_app/guide/search'
      path: '/guide/search'
      fullPath: '/guide/search'
      preLoaderRoute: typeof AppGuideSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide/saved': {
      id: '/_app/guide/saved'
      path: '/guide/saved'
      fullPath: '/guide/saved'
      preLoaderRoute: typeof AppGuideSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/safety': {
      id: '/_app/assess/safety'
      path: '/assess/safety'
      fullPath: '/assess/safety'
      preLoaderRoute: typeof AppAssessSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/red-flag': {
      id: '/_app/assess/red-flag'
      path: '/assess/red-flag'
      fullPath: '/assess/red-flag'
      preLoaderRoute: typeof AppAssessRedFlagRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/processing': {
      id: '/_app/assess/processing'
      path: '/assess/processing'
      fullPath: '/assess/processing'
      preLoaderRoute: typeof AppAssessProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/location': {
      id: '/_app/assess/location'
      path: '/assess/location'
      fullPath: '/assess/location'
      preLoaderRoute: typeof AppAssessLocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/activity': {
      id: '/_app/assess/activity'
      path: '/assess/activity'
      fullPath: '/assess/activity'
      preLoaderRoute: typeof AppAssessActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover/summary/$id': {
      id: '/_app/recover/summary/$id'
      path: '/recover/summary/$id'
      fullPath: '/recover/summary/$id'
      preLoaderRoute: typeof AppRecoverSummaryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover/session/$id': {
      id: '/_app/recover/session/$id'
      path: '/recover/session/$id'
      fullPath: '/recover/session/$id'
      preLoaderRoute: typeof AppRecoverSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover/activity/$id': {
      id: '/_app/recover/activity/$id'
      path: '/recover/activity/$id'
      fullPath: '/recover/activity/$id'
      preLoaderRoute: typeof AppRecoverActivityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide/article/$id': {
      id: '/_app/guide/article/$id'
      path: '/guide/article/$id'
      fullPath: '/guide/article/$id'
      preLoaderRoute: typeof AppGuideArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/result/$id': {
      id: '/_app/assess/result/$id'
      path: '/assess/result/$id'
      fullPath: '/assess/result/$id'
      preLoaderRoute: typeof AppAssessResultIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/questions/$type': {
      id: '/_app/assess/questions/$type'
      path: '/assess/questions/$type'
      fullPath: '/assess/questions/$type'
      preLoaderRoute: typeof AppAssessQuestionsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/followup/$id': {
      id: '/_app/assess/followup/$id'
      path: '/assess/followup/$id'
      fullPath: '/assess/followup/$id'
      preLoaderRoute: typeof AppAssessFollowupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assess/care-plan/$id': {
      id: '/_app/assess/care-plan/$id'
      path: '/assess/care-plan/$id'
      fullPath: '/assess/care-plan/$id'
      preLoaderRoute: typeof AppAssessCarePlanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppAssessActivityRoute: typeof AppAssessActivityRoute
  AppAssessLocationRoute: typeof AppAssessLocationRoute
  AppAssessProcessingRoute: typeof AppAssessProcessingRoute
  AppAssessRedFlagRoute: typeof AppAssessRedFlagRoute
  AppAssessSafetyRoute: typeof AppAssessSafetyRoute
  AppGuideSavedRoute: typeof AppGuideSavedRoute
  AppGuideSearchRoute: typeof AppGuideSearchRoute
  AppAssessIndexRoute: typeof AppAssessIndexRoute
  AppGuideIndexRoute: typeof AppGuideIndexRoute
  AppRecoverIndexRoute: typeof AppRecoverIndexRoute
  AppAssessCarePlanIdRoute: typeof AppAssessCarePlanIdRoute
  AppAssessFollowupIdRoute: typeof AppAssessFollowupIdRoute
  AppAssessQuestionsTypeRoute: typeof AppAssessQuestionsTypeRoute
  AppAssessResultIdRoute: typeof AppAssessResultIdRoute
  AppGuideArticleIdRoute: typeof AppGuideArticleIdRoute
  AppRecoverActivityIdRoute: typeof AppRecoverActivityIdRoute
  AppRecoverSessionIdRoute: typeof AppRecoverSessionIdRoute
  AppRecoverSummaryIdRoute: typeof AppRecoverSummaryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppAssessActivityRoute: AppAssessActivityRoute,
  AppAssessLocationRoute: AppAssessLocationRoute,
  AppAssessProcessingRoute: AppAssessProcessingRoute,
  AppAssessRedFlagRoute: AppAssessRedFlagRoute,
  AppAssessSafetyRoute: AppAssessSafetyRoute,
  AppGuideSavedRoute: AppGuideSavedRoute,
  AppGuideSearchRoute: AppGuideSearchRoute,
  AppAssessIndexRoute: AppAssessIndexRoute,
  AppGuideIndexRoute: AppGuideIndexRoute,
  AppRecoverIndexRoute: AppRecoverIndexRoute,
  AppAssessCarePlanIdRoute: AppAssessCarePlanIdRoute,
  AppAssessFollowupIdRoute: AppAssessFollowupIdRoute,
  AppAssessQuestionsTypeRoute: AppAssessQuestionsTypeRoute,
  AppAssessResultIdRoute: AppAssessResultIdRoute,
  AppGuideArticleIdRoute: AppGuideArticleIdRoute,
  AppRecoverActivityIdRoute: AppRecoverActivityIdRoute,
  AppRecoverSessionIdRoute: AppRecoverSessionIdRoute,
  AppRecoverSummaryIdRoute: AppRecoverSummaryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
